# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode 
  database: careersmob_development
  pool: 5
  host: localhost

production: 
  adapter: postgresql
  encoding: unicode 
  database: careersmob_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: careersmob_development
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

default: &default
  adapter: postgresql
  encoding: unicode
  database: careersmob_production
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5